config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    collection do

      get :join
      post :join_group
    end

    member do
      get :dashboard
    end



     resources :shopping_lists, only: [:index, :new, :create, :show] do
        collection do
        get :new_item
        get :pre_selection
        end

        resources :bought_items, only: [:index, :new, :create, :show]

      end

    resources :tasks, only: [:index, :new, :create, :show] do
      member do
        get :usertasks
        patch :progress
        patch :finish_task

      end
    end

    resources :fixed_costs, only: [:index, :new, :create, :show]
  end
  get "options", to: "pages#options", as: "options"
  get "landing", to: "pages#landing"
  # get "groups/:id", to: "groups#show", as: "group"
  # get "usertasks/:id", to: "tasks#userstasks", as: "usertasks"
  # get "groups/:group_id", to: "shopping_lists#new_item", as: "newitem"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :group
  validates :group, presence: true
  default_scope -> { order('created_at DESC') }
  scope :completed, -> { where(completed: true) }
  scope :incomplete,-> { where(completed: false) }


  include PgSearch::Model
  pg_search_scope :search_by_task_and_name,
    against: [ :name, :assigned_to_id ],
    using: {
      tsearch: { prefix: true }, # <-- now `superman batm` will return something!
}

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def index
    #   if params[:my_user]
    #  @tasks = Task.where(group_id: params[:group_id])
    @tasks = Task.where("deadline >= ?", Date.today).where(group_id: params[:group_id]).where(done: nil)
    @missed_tasks = Task.where("deadline < ?", Date.today).where(group_id: params[:group_id])
    @done_tasks = Task.where("deadline >= ?", Date.today).where(group_id: params[:group_id]).where(done: true)

    if params[:query].present?
      @tasks = Task.search_by_task_and_name(params[:query])
    else
      @tasks = Task.where(id: @tasks)
    end
    #   @tasks = @group.tasks.map do |task|
    #     task.user_id == params[:my_user]
    #   end


    #   @upcoming_tasks = Task.where("deadline > ?", Date.today).where(user_id: params[:my_user]).where(group_id: @group.id)
    #   @missed_tasks = Task.where("deadline < ?", Date.today).where(user_id: params[:my_user]).where(group_id: @group.id)
    #   # @my_date = Date.parse(Date.today).strftime("%d/%m/%Y")
    # else
    #   @group = Group.find(current_user.group_id)
    #   @tasks = @group.tasks
    #   @upcoming_tasks = Task.where("deadline > ?", Date.today).where(user_id: current_user.id).where(group_id: @group.id)
    #   @missed_tasks = Task.where("deadline < ?", Date.today).where(user_id: current_user.id).where(group_id: @group.id)
    # end
    # @upcoming_tasks = Task.where("deadline > ?", Date.today).where(user_id: current_user.id).where(group_id: @group.id)
    # This for user task dashboard
  end

  def usertasks
    @group = Group.find(params[:group_id])
    @task = Task.find(params[:id])
    @owner_of_task = @task.assigned_to_id
    @user = User.find(@owner_of_task)
    @my_tasks = Task.where(assigned_to_id:@owner_of_task)

  end

  def new

    @group = Group.find(params[:group_id])
    @user_ids_in_this_group =  MultipleGroup.where(group_id:  @group.id).pluck(:user_id)
    @user_profiles = User.where(id: @user_ids_in_this_group)
    @task = Task.new # Needed to instantiate the form_with
  end


  def create
    @task = Task.new(task_params)
    @group = Group.find(params[:group_id])
    @task.group = @group
    # @user = current_user
    # @task.user = @user

    @task.save


   redirect_to group_tasks_path(@group) # group_id task_id
  end

  def show
    @task = Task.find(params[:id])
    @group = Group.find(params[:group_id])
    @users = MultipleGroup.where(group_id:  @group.id).pluck(:user_id)
  end

  def finish_task
    @task = Task.find(params[:id])
    @group = Group.find(params[:group_id])
    @task.done = true
    @task.save

    redirect_to group_tasks_path(@group)
  end




  def progress
    @group = Group.find(params[:group_id])
    @task = Task.find(params[:id])

    @task.done = true

    @task.save

    redirect_to group_task_path(@group)
  end




  private

  def task_params
    params.require(:task).permit(:name, :assigned_to_id, :done, :urgent, :comments, :deadline, :recurrence, :recurring)
  end


end

app/views/tasks/_card_tasks_back_index.html.erb
   <div class="container row d-flex justifycontent-between">
    <% @missed_tasks.each do |task| %>
      <div class="card_tasks_up_index">
        <div class="card-a"><%= "X" %></div>
        <div class="card-b"><%= task.name %></div>
        <div class="card-c"><%= task.deadline.strftime("%d.%m.%Y") %></div>
        <div class="card-d">
          <div class="current_user_index_avatar">
          <%= link_to   group_tasks_path(current_user.group_id, :my_user => current_user.id)  do %>
             <i class="fa-solid fa-dog fa-xl" style="color:#DF6C4F" class="align-center"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

  </div>

app/views/tasks/_card_tasks_up_index.html.erb
   <div class="container row d-flex justifycontent-between">
    <% @upcoming_tasks.each do |task| %>
      <div class="card_tasks_up_index">
        <div class="card-a"><%= link_to task.done ? "Done" : "Not Done", progress_group_task_path(current_user.group_id, task.id), data: {turbo_method: :patch}, style:  "background-color: #{task.done ? "green" : "red"}" %></div>
        <div class="card-b"><%= task.name %></div>
        <div class="card-c"><%= task.deadline.strftime("%d.%m.%Y") %></div>
        <div class="card-d">
          <div class="current_user_index_avatar">
          <%= link_to group_tasks_path(current_user.group_id, :my_user => current_user.id)  do %>
          <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar" %>
              <% else %>
              <h5>Placeholder</h5>
          <% end %>

           <% end %>
          </div>
        </div>
      </div>

    <% end %>

  </div>

app/views/tasks/_missed_task_card.html.erb
<div class="task-card-index-missed mb-3">
  <div class="task-owner pt-3">
    <div class="task-owner-bg-color" style="background-color: <%= ["#ffc1c6", "#c59ffe", "#fed464", "#c1d9f9", "#d7fafb"].sample %>">
      <%= link_to usertasks_group_task_path(params[:group_id], task) do %>
      <%= image_tag "default-avatar.png" %>
      <% end %>
    </div>
    <h6 class="d-none" style="color:#c87f90"><%= User.find(task.assigned_to_id).first_name %>'s Task</h6>
    <h5 class="" style="font-weight: 400; color: #b8b8b8;"> <%= ["😡", "😈", "🖕", "💩", "💣"].sample %> <%#= TimeDifference.between(task.created_at, Time.now).in_minutes %> </h5>
  </div>

  <h6><%= User.find(task.assigned_to_id).first_name %>'s Task</h6>
  <div class="task-detail-missed mb-3 mt-3">
  <h6 style="color: #c87f90;"> <%= task.deadline.strftime("%d.%m.%Y") %> </h6>
  <h6 style="color: #c87f90;"><%= task.name %></h6>
  </div>

  <div class="task-options d-none mb-3">
    <div class="task-options-flex">
     <%= link_to usertasks_group_task_path(params[:group_id], task), data: {turbo_method: :patch} do %>
        <div class="button-circle" style="background-color:#bef8d5; margin-right: 10px">
          <i class="fa-solid fa-check"></i>
        </div>
      <% end %>

      <div class="button-circle" style="background-color:#fecacd">
        <i class="fa-solid fa-xmark" style="color:#af2632"></i>
      </div>

      </div>
  </div>
</div>

app/views/tasks/_progressbar.html.erb
<a href="https://github.com/aorcsik/radial-progress-bar" target="_blank"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>
<br>
<section>
  <div id="example1" class="example"></div>
  <h2>Radial Progress Bar</h2>
  <p>The default radial progress bar. Blue progress bar, semi-transparent background path, 40px progress text in the center. Subsequent percentage settings can be queued.</p>
  <!-- <p><strong>HTML</strong></p>
  <pre>
&lt;div id="example1"&gt;&lt;/div&gt;</pre>
  <p><strong>JavaScript</strong></p>
  <pre>
jQuery("#example1").radialProgress("init", {
  'size': 100,
  'fill': 5
}).radialProgress("to", {'perc': 50})
  .radialProgress("to", {'perc': 30})
  .radialProgress("to", {'perc': 100});</pre>-->
</section>
<section>
  <div id="pie" class="example" style="width: 100px;"></div>
  <h2>Simple Pie Chart</h2>
  <p>Multiple radial progress bars layered on top and offsetted by each other. Values are visible in the center as a list. Data is loaded in initialization.</p>
</section>
<section>
  <div id="multi" class="example" style="width: 100px;"></div>
  <h2>Concentric Bars</h2>
  <p>Multiple radial progress bars in concentric circles around each other. Defined as regular radial progress bar, empty on init, each bar can be set separately or together. </p>
  <p>With ranges and periodic updates the clock on the left can be easily created.</p>
</section>
<section>
  <h2>Inline Icons</h2>
  With a small size and fill settings and transparent text inline icon progress bar <span id="smallrad" style="display: inline-block;"></span> or pie chart <span id="smallpie" style="display: inline-block;"></span> can be created.</span>
</section>

app/views/tasks/_task_card.html.erb
<div class="task-card-index mb-3">
  <div class="task-owner pt-3">
    <div class="task-owner-bg-color" style="background-color: <%= ["#ffc1c6", "#c59ffe", "#fed464", "#c1d9f9", "#d7fafb"].sample %>">
      <%= link_to usertasks_group_task_path(params[:group_id], task) do %>
        <% if User.find(task.assigned_to_id).photo.attached? %>
          <%= cl_image_tag User.find(task.assigned_to_id).photo.key, class: "group-member-avatar" %>
        <% else %>
          <%= image_tag "default-avatar.png", class: "group-member-avatar" %>
        <% end %>
      <% end %>
    </div>
    <h6><%= User.find(task.assigned_to_id).first_name %>'s Task</h6>
    <% timedifferece = TimeDifference.between(task.created_at, Time.now).in_minutes %>
      <% if timedifferece < 60 %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= TimeDifference.between(task.created_at, Time.now).in_minutes.round %> Mins ago</h6>
        <% elsif timedifferece >= 60 && timedifferece <= 1440 %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= timedifferece = TimeDifference.between(task.created_at, Time.now).in_hours.round %> Hours ago</h6>
        <% else %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= timedifferece = TimeDifference.between(task.created_at, Time.now).in_days.round %> Days ago</h6>
        <% end %>
  </div>

  <div class="task-detail mb-3 mt-3">
  <h6 style="color: #6f9cb6;"> <%= task.deadline.strftime("%d.%m.%Y") %> </h6>
  <h6 style="color: #0f5779;">  <%= task.name %></h6>
  </div>

  <div class="task-options mb-3">
    <div class="task-options-flex">
     <%= link_to usertasks_group_task_path(params[:group_id], task), data: {turbo_method: :patch} do %>
        <div class="button-circle" style="background-color:#bef8d5; margin-right: 10px">
          <i class="fa-solid fa-check"></i>
        </div>
      <% end %>

      <div class="button-circle" style="background-color:#fecacd">
        <i class="fa-solid fa-xmark" style="color:#af2632"></i>
      </div>

      </div>
  </div>
</div>

app/views/tasks/_tasks_index_bg_card.html.erb
<div class="container">
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
</div>

app/views/tasks/index.html.erb
<div class="return-arrow">
    <%= link_to group_path(params[:group_id]) do %>
    <i class="fa-solid fa-chevron-left" style="color:#21C560; font-size: 35px; cursor: pointer;" class="align-center"></i>
    <% end %>
</div>
<h1 class="title mt-5">TASKS</h1>
  <div class="mt-5 mb-5" style="width: 100%; text-align:center">
      <%= link_to new_group_task_path(params[:group_id]) do %>
            <i class="fa-solid fa-square-plus fa-2xl" style="color:#23c560; text-align:center; font-size:50px"></i>
      <% end %>
  </div>

  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: group_tasks_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

    <div class="index-tasks-wrapper" data-controller="accordion">

  <h1 class="mb-3" style="color:#adadaf">Upcoming Tasks</h1>
    <% @tasks.each do |task| %>
      <%= render "task_card", task:task %>
    <% end %>


        <%# <div class="card-show-d"><%= render "shared/current_user_index_avatar" %>
        <%# <div class="card-show-b"><%= @task.deadline.strftime("%d.%m.%Y") %>

     <button class="accordion mb-3" data-accordion-target="accordion"><h1 style="color:#adadaf">Missed Tasks</h1></button>
        <div class="panel">

    <% @missed_tasks.each do |task| %>
      <%= render "missed_task_card", task:task %>
    <% end %>


  </div>



</div>
<%# <div class="d-flex align-items-center flex-column">

  <h3>Manage your tasks</h3>
  <%= link_to new_group_task_path do %>
      <%# <div class="container">
        <i class="fa-solid fa-square-plus fa-2xl" style="color:#DF6C4F" class="align-center" ></i>
      </div>
  <% end %>


  <%# <p>Upcoming </p>
  <div class="container tasks_index_bg_card">
    <%= render "tasks/card_tasks_up_index"%>
  <%# </div> %>

  <%# <p>Backlog</p>
    <div class="container tasks_index_bg_card">
      <%= render "tasks/card_tasks_back_index" %>

    <%# </div>
 </div> %>

app/views/tasks/new.html.erb
<div class="return-arrow">
  <%= link_to group_tasks_path do %>
  <i class="fa-solid fa-chevron-left" style="color:#21C560; font-size: 35px; cursor: pointer;" class="align-center"></i>
  <% end %>
</div>
<h1 class="title">👾<br>Create a new Task</h1>

    <%= simple_form_for [@group, @task], class: "new-group" do |f| %>
      <%= f.input :name, placeholder: "e.g. Clean something", required: true%>
      <%= f.input :assigned_to_id, collection: @user_profiles, label_method: :first_name, placeholder: "Pick a housemate", required: true, label: "Assign to"%>
      <%= f.input :urgent, label: "Urgent 🚨" %>
      <%= f.input :comments, required: true %>
      <%= f.input :deadline, required: true%>



      <%= f.submit :class => "action btn btn-primary", style: "width: 100%" %>
    <% end %>


<div>

app/views/tasks/show.html.erb
<h1 class="title mt-5">TASKS</h1>





    <div class="show-tasks-wrapper">

        <%# <div class="card-show-d"><%= render "shared/current_user_index_avatar" %>
        <%# <div class="card-show-b"><%= @task.deadline.strftime("%d.%m.%Y") %></div>


        <div class="card-show-d d-flex justify-content-center"><%= render "shared/current_user_index_avatar" %></div>
        <div class="card-show-a al d-flex justify-content-center"><%= @task.deadline.strftime("%d.%m.%Y") %></div>
        <div class="card-show-c d-flex justify-content-center"><%= @task.name %></div>
        <div class="card-show-c d-flex justify-content-center"><%= @task.comments %></div>
        <div class="card-show-c d-flex justify-content-center">
        <% if @task.done? == true %>
        <%= "done" %>
        <% else %>
        <%= "to be done" %>
        <% end %>
        </div>



    </div>




      <div>
        <%= link_to "See all tasks", group_tasks_path, :class => "btn btn-primary" %>
      </div>

app/views/tasks/userstasks.html.erb
<h1>Hello from Usertasks</h1>
  <h1 class="mb-3" style="color:#adadaf">Upcoming Tasks</h1>
    <% @my_tasks.each do |task| %>
      <div class="task-card-index mb-3">
  <div class="task-owner pt-3">
    <div class="task-owner-bg-color" style="background-color: <%= ["#ffc1c6", "#c59ffe", "#fed464", "#c1d9f9", "#d7fafb"].sample %>">
      <%= link_to usertasks_path(@group, @user) do %>
                <% if @user.photo.attached? %>
                    <%= cl_image_tag @user.photo.key, class: "group-member-avatar" %>
                    <% else %>
                    <%= image_tag "default-avatar.png", class: "group-member-avatar" %>
                <% end %>
      <% end %>
    </div>
    <h6><%= User.find(task.assigned_to_id).first_name %>'s Task</h6>
    <% timedifferece = TimeDifference.between(task.created_at, Time.now).in_minutes %>
      <% if timedifferece < 60 %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= TimeDifference.between(task.created_at, Time.now).in_minutes.round %> Mins ago</h6>
        <% elsif timedifferece >= 60 && timedifferece <= 1440 %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= timedifferece = TimeDifference.between(task.created_at, Time.now).in_hours.round %> Hours ago</h6>
        <% else %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= timedifferece = TimeDifference.between(task.created_at, Time.now).in_days.round %> Days ago</h6>
        <% end %>
  </div>

  <div class="task-detail mb-3 mt-3">
  <h6 style="color: #6f9cb6;"> <%= task.deadline.strftime("%d.%m.%Y") %> </h6>
  <h6 style="color: #0f5779;">  <%= task.name %></h6>
  </div>

  <div class="task-options mb-3">
    <div class="task-options-flex">
     <%= link_to finish_task_group_task_path(@group, task), data: {turbo_method: :patch} do %>
        <div class="button-circle" style="background-color:#bef8d5; margin-right: 10px">
          <i class="fa-solid fa-check"></i>
        </div>
      <% end %>

      <div class="button-circle" style="background-color:#fecacd">
        <i class="fa-solid fa-xmark" style="color:#af2632"></i>
      </div>

      </div>
  </div>
</div>

    <% end %>

app/views/tasks/usertasks.html.erb
<h1><%= @user.first_name %>'s tasks</h1>
  <h1 class="mb-3" style="color:#adadaf">Upcoming Tasks</h1>
    <% @my_tasks.each do |task| %>
      <div class="task-card-index mb-3">
  <div class="task-owner pt-3">
    <div class="task-owner-bg-color" style="background-color: <%= ["#ffc1c6", "#c59ffe", "#fed464", "#c1d9f9", "#d7fafb"].sample %>">
      <%= link_to usertasks_group_task_path(@group, task.assigned_to_id) do %>
                <% if @user.photo.attached? %>
                    <%= cl_image_tag @user.photo.key, class: "group-member-avatar" %>
                    <% else %>
                    <%= image_tag "default-avatar.png", class: "group-member-avatar" %>
                <% end %>
      <% end %>
    </div>
    <h6><%= User.find(task.assigned_to_id).first_name %>'s Task</h6>
    <% timedifferece = TimeDifference.between(task.created_at, Time.now).in_minutes %>
      <% if timedifferece < 60 %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= TimeDifference.between(task.created_at, Time.now).in_minutes.round %> Mins ago</h6>
        <% elsif timedifferece >= 60 && timedifferece <= 1440 %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= timedifferece = TimeDifference.between(task.created_at, Time.now).in_hours.round %> Hours ago</h6>
        <% else %>
          <h6 style="font-weight: 400; color: #b8b8b8;">Created <%= timedifferece = TimeDifference.between(task.created_at, Time.now).in_days.round %> Days ago</h6>
        <% end %>
  </div>

  <div class="task-detail mb-3 mt-3">
  <h6 style="color: #6f9cb6;"> <%= task.deadline.strftime("%d.%m.%Y") %> </h6>
  <h6 style="color: #0f5779;">  <%= task.name %></h6>
  </div>

  <div class="task-options mb-3">
    <div class="task-options-flex">
     <%= link_to finish_task_group_task_path(@group, task), data: {turbo_method: :patch} do %>
        <div class="button-circle" style="background-color:#bef8d5; margin-right: 10px">
          <i class="fa-solid fa-check"></i>
        </div>
      <% end %>

      <div class="button-circle" style="background-color:#fecacd">
        <i class="fa-solid fa-xmark" style="color:#af2632"></i>
      </div>

      </div>
  </div>
</div>

    <% end %>