config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    collection do

      get :join
      post :join_group
    end

    member do
      get :dashboard
    end



     resources :shopping_lists, only: [:index, :new, :create, :show] do
        collection do
        get :new_item
        get :pre_selection
        end

        resources :bought_items, only: [:index, :new, :create, :show]

      end

    resources :tasks, only: [:index, :new, :create, :show] do
      member do
        get :usertasks
        patch :progress
        patch :finish_task

      end
    end

    resources :fixed_costs, only: [:index, :new, :create, :show]
  end
  get "options", to: "pages#options", as: "options"
  get "landing", to: "pages#landing"
  # get "groups/:id", to: "groups#show", as: "group"
  # get "usertasks/:id", to: "tasks#userstasks", as: "usertasks"
  # get "groups/:group_id", to: "shopping_lists#new_item", as: "newitem"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, optional: true
  has_many :tasks
  has_many :multiple_groups
  has_one  :shopping_list
  # has_many :roomies, :class_name => "User"
  has_one_attached :photo

  include PgSearch::Model
  multisearchable against: [ :name, :description ]


  include PgSearch::Model
    pg_search_scope :search_by_group_and_description,
      against: [ :name, :description ],
      using: {
        tsearch: { prefix: true }, # <-- now `superman batm` will return something!
  }

  # include PgSearch::Model
  #   pg_search_scope :search_by_name, lambda { |name, query|
  #     raise ArgumentError unless [:name].include?(name)
  #     {
  #       against: name_part,
  #       query: query
  #     }
  #   }



end


# include PgSearch::Model
# pg_search_scope :search_by_name, lambda { |name_part, query|
#   raise ArgumentError unless [:first, :last].include?(name_part)
#   {
#     against: name_part,
#     query: query
#   }
# }
# end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    group_ids = MultipleGroup.where(user:current_user).pluck(:group_id)
    @groups = Group.where(id: group_ids)

    if params[:query].present?
      @groups = Group.search_by_group_and_description(params[:query])
    else
      @groups = Group.where(id: group_ids)
    end

  end

  def show
    @group = Group.find(params[:id])
    @shopping_list =  @group.shopping_list
    find_user_ids = MultipleGroup.where(group: @group).pluck(:user_id)
    @group_members = User.where(id:find_user_ids)
    @group_tasks = @group.tasks
    @group_shopping_list = @group.shopping_list
    @bought_items = BoughtItem.where(shopping_list_id: @group_shopping_list.id )

    @total_tasks = @group_tasks.length
    @finished_tasks = @group_tasks.select{|task| task.done}.length
    @not_finished_tasks = @group_tasks.reject{|task| task.done}.length

    @statusbar_done_width= (@finished_tasks * 100) / 3
    @stausbar_not_done_witdth = 100 -  @statusbar_done_width

    @total = @bought_items.map do |item|
          item.product.price
    end.reduce(0){|a,b| a+b }



  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @user = current_user
    # @task.user = @user

    @group.save
    @user.group_id = @group.id
    MultipleGroup.create(user_id: current_user.id, group_id: @group.id)
    ShoppingList.create(group: @group)
    @user.save
    redirect_to groups_path
  end

def join_a_group
    @groups = Group.all
    if params[:query].present?
      @groups = @groups.where(name: params[:query])
    end
end

  def join
    @groups = Group.all
  end

  def join_group

    @group = Group.find(params[:user][:group_id])
    @multigroup = MultipleGroup.new()
    @multigroup.group =  @group
    @multigroup.user =  current_user

    if @multigroup.save

      redirect_to group_path(@group)
    else
      redirect_to join_groups_path
    end
  end

  def dashboard
    @shopping_list = ShoppingList.find_by(group_id: params[:id])
    @bought_items = BoughtItem.where(shopping_list: @shopping_list)
    @total_products =  @bought_items.map{|item| item.product.price}.reduce(0){|a,b| a+b}
    @find_users = MultipleGroup.where(group: params[:id]).pluck(:user_id)
    @user_products = BoughtItem.where(user_id:@find_users)

    # @sums = @user_products.group(@find_users).includes(:product).sum(:price)
    @user_sums = @bought_items.group(:user_id).includes(:product).sum(:price)

  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :passcode, :photo)
  end

end

app/views/groups/_alt.show.html.erb
<div class="container bootstrap snippets bootdeys">
<div class="row">
    <div class="col-md-4 col-sm-6 content-card">
        <div class="card-big-shadow">
            <div class="card card-just-text" data-background="color" data-color="blue" data-radius="none">
                <div class="content">
                    <h6 class="category">Best cards</h6>
                    <h4 class="title"><a href="#">Blue Card</a></h4>
                    <p class="description">What all of these have in common is that they're pulling information out of the app or the service and making it relevant to the moment. </p>
                </div>
            </div> <!-- end card -->
        </div>
    </div>

    <div class="col-md-4 col-sm-6 content-card">
        <div class="card-big-shadow">
            <div class="card card-just-text" data-background="color" data-color="green" data-radius="none">
                <div class="content">
                    <h6 class="category">Best cards</h6>
                    <h4 class="title"><a href="#">Green Card</a></h4>
                    <p class="description">What all of these have in common is that they're pulling information out of the app or the service and making it relevant to the moment. </p>
                </div>
            </div> <!-- end card -->
        </div>
    </div>

    <div class="col-md-4 col-sm-6 content-card">
        <div class="card-big-shadow">
            <div class="card card-just-text" data-background="color" data-color="yellow" data-radius="none">
                <div class="content">
                    <h6 class="category">Best cards</h6>
                    <h4 class="title"><a href="#">Yellow Card</a></h4>
                    <p class="description">What all of these have in common is that they're pulling information out of the app or the service and making it relevant to the moment. </p>
                </div>
            </div> <!-- end card -->
        </div>
    </div>

    <div class="col-md-4 col-sm-6 content-card">
        <div class="card-big-shadow">
            <div class="card card-just-text" data-background="color" data-color="brown" data-radius="none">
                <div class="content">
                    <h6 class="category">Best cards</h6>
                    <h4 class="title"><a href="#">Brown Card</a></h4>
                    <p class="description">What all of these have in common is that they're pulling information out of the app or the service and making it relevant to the moment. </p>
                </div>
            </div> <!-- end card -->
        </div>
    </div>

    <div class="col-md-4 col-sm-6 content-card">
        <div class="card-big-shadow">
            <div class="card card-just-text" data-background="color" data-color="purple" data-radius="none">
                <div class="content">
                    <h6 class="category">Best cards</h6>
                    <h4 class="title"><a href="#">Purple Card</a></h4>
                    <p class="description">What all of these have in common is that they're pulling information out of the app or the service and making it relevant to the moment. </p>
                </div>
            </div> <!-- end card -->
        </div>
    </div>

    <div class="col-md-4 col-sm-6 content-card">
        <div class="card-big-shadow">
            <div class="card card-just-text" data-background="color" data-color="orange" data-radius="none">
                <div class="content">
                    <h6 class="category">Best cards</h6>
                    <h4 class="title"><a href="#">Orange Card</a></h4>
                    <p class="description">What all of these have in common is that they're pulling information out of the app or the service and making it relevant to the moment. </p>
                </div>
            </div> <!-- end card -->
        </div>
    </div>
</div>
</div>

app/views/groups/_group_card.html.erb
   <% @groups.each do |group| %>
      <div class="group-card mt-2 mb-4">
        <div class="group-card-wrapper">

          <% if group.photo.attached? %>
              <div class="bg-image mb-4" style="background-image:url('<%= cl_image_path group.photo.key %>')"></div>
              <% else %>
              <h6>Default Image</h6>
          <% end %>

            <h3><%= group.name %></h3>
            <div class="group-info">
            <i class="fa-solid fa-user-group"></i>
            <h6><%= MultipleGroup.where(group: group).length %></h6>
            </div>
            <div class="group-action mt-3">
              <h6><%= group.description %></h6>
               <%= link_to group_path(group) do%>
                    <i class="fa-solid fa-chevron-right"></i>
              <% end %>

            </div>
          </div>
        </div>
  <% end %>

app/views/groups/dashboard.html.erb
<div data-controller="charter" style="position: relative">
  <h1 style="position: absolute;
bottom: 35%;
right: 41%;
text-align: center;
">Total<br>630 €</h1>
  <canvas data-charter-target="canvas" id="myChart"></canvas>
</div>

<% @user_products.each do |item| %>
    <%= item.user_id %>
<% end %>

app/views/groups/index.html.erb
  <h3 class="title mt-5 mb-4">My Groups</h3>
  <div class="mt-5 mb-5" style="width: 100%; text-align:center">
  <%= link_to new_group_path do %>
        <i class="fa-solid fa-square-plus fa-2xl" style="color:#23c560; text-align:center; font-size:50px"></i>
  <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: groups_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>



    <div class="group-grid">
      <%= render "group_card" %>
    </div>

app/views/groups/join.html.erb
<div class="d-flex align-items-center flex-column">

  <h1>Join a group</h1>

    <div class="container tasks_index_bg_card">





    <%= simple_form_for current_user, url: join_group_groups_path, method: :post do |f| %>
      <%= f.input :group_id, collection: @groups, label_method: :name, prompt: 'Pick your group' %>
      <%= f.button :submit, "Join" %>
    <% end %>

    </div>
</div>

app/views/groups/new.html.erb
<h1 class="title mt-4 mb-3">👾<br>Create your Group</h1>

<%= simple_form_for @group, class:"new-group" do |f| %>
  <%= f.input :name, class:"mb-4" %>
  <%= f.input :passcode, class:"mb-4" %>
  <%= f.input :description, class:"mb-4" %>
  <%= f.input :photo, as: :file, class:"mb-4" %>


  <%= f.submit class: "action" %>


<% end %>

app/views/groups/show.html.erb
<div class="animated fadeInDown">

<h1 class="title mt-4"><br><span style="color: #c7c7c8;"><%= @group.name %></span></h1>
<div class="group-show-wrapper">
  <div class="group-show-image-holder" style="background-color: <%= ["#ffc1c6", "#c59ffe", "#fed464", "#c1d9f9", "#d7fafb"].sample %> ">
      <% if @group.photo.attached? %>
           <%= cl_image_tag @group.photo.key, class: "group-show-avatar" %>
      <% end %>

  </div>


   <div class="group-members">



          <h5 style="font-weight:300" class="mt-2">Members</h5>
            <div class="group-members-flex">
              <% @group_members.each do |user| %>
                <div class="group-member-image-holder" style="background-color: <%= ["#ffc1c6", "#c59ffe", "#fed464", "#c1d9f9", "#d7fafb"].sample %> ">
                <% if user.photo.attached? %>
                    <%= cl_image_tag user.photo.key, class: "group-member-avatar" %>
                    <% else %>
                    <%= image_tag "default-avatar.png", class: "group-member-avatar" %>
                <% end %>
                </div>
              <% end %>
           </div>
    </div>

  </div>

   <div class="option-card-group mt-4" style="display: flex;">
        <h5>Total pending payment:</h5>
        <h2>59,02 €</h2>
        <%= link_to "Add Cost", group_fixed_costs_path(@group) %>
   </div>
</div>
   <div class="more-card-holder mt-4">

       <div class="option-card-group animated fadeInLeft" style="position: relative;">
       <p style="position: absolute;right: 11px;top: 9px;"> <%= @not_finished_tasks  %> Tasks</p>
       <%= link_to  group_tasks_path(@group) do %>
          <div class="icon-holder">
            <i class="fa-solid fa-broom"></i>
          </div>
        <% end %>
          <h5 class="mt-3">Duties</h5>
      </div>

      <div class="option-card-group animated fadeInRight" style="position: relative;">
      <p style="position: absolute;right: 11px;top: 9px;"> <%= @bought_items.length  %> Items</p>

          <%= link_to group_shopping_lists_path(@group) do%>
        <div class="icon-holder">
            <i class="fa-solid fa-pizza-slice"></i>
          </div>
          <% end %>
          <h5 class="mt-3">Food</h5>
      </div>

   </div>

<div class="option-card-group mb-5 mt-5 animated fadeInUp">
      <h2 class="mb-3">Quick Stats</h2>

    <div>
      <h6 class="mt-2 mb-3">Completion</h6>
    </div>
      <div class="completion">
        <div class="statusbar-done" style="width: <%= @statusbar_done_width %>%"></div>
        <div class="statusbar-left" style="width: <%= @stausbar_not_done_witdth %>%"></div>
      </div>

      <div>



        <h6 class="mt-4 mb-3">Latest Tasks</h6>
        <% if @group_tasks.first(2).empty? %>

        <div class="group-show-task-card">
              <div class="group-task-show-icon-wrapper">
                <i class="fa-regular fa-bell" style="color:#f16db8"></i>
              </div>
              <p>Create your Task</p>
            </div>

            <% else %>
        <% @group_tasks.first(2).each do |task| %>
            <div class="group-show-task-card">
              <div class="group-task-show-icon-wrapper">
                <i class=" <%= ["fa-regular fa-bell", "fa-solid fa-bolt", "fa-regular fa-lightbulb", "fa-solid fa-explosion", "fa-solid fa-leaf"].sample %>" style="color:#f16db8"></i>
              </div>
              <p><%= task.name  %></p>
            </div>
          <% end %>

        <% end %>

        </div>







  <h6 class="mt-2 mb-3">Latest Items</h6>
        <div>
        <% if @bought_items.empty? %>
          <div class="group-show-task-card">
              <div class="group-task-show-icon-wrapper">
                <i class="fa-solid fa-cow" style="color: #c283f7"></i>
              </div>
              <p>Milk</p>
            </div>
        <% else %>
          <%  @bought_items.first(2).each do |item| %>
            <div class="group-show-task-card">
              <div class="group-task-show-icon-wrapper" style="background-color: #d6f7e5;">
                <i class="<%= ["fa-solid fa-bowl-food", "fa-solid fa-utensils", "fa-solid fa-pizza-slice", "fa-solid fa-cookie-bite", "fa-solid fa-hotdog"].sample %>" style="color:#49795f"></i>
              </div>
              <p><%= item.product.name %></p>

            </div>
          <% end %>
        <% end %>

        </div>
</div>





















</div>