config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    collection do

      get :join
      post :join_group
    end

    member do
      get :dashboard
    end



     resources :shopping_lists, only: [:index, :new, :create, :show] do
        collection do
        get :new_item
        get :pre_selection
        end

        resources :bought_items, only: [:index, :new, :create, :show]

      end

    resources :tasks, only: [:index, :new, :create, :show] do
      member do
        get :usertasks
        patch :progress
        patch :finish_task

      end
    end

    resources :fixed_costs, only: [:index, :new, :create, :show]
  end
  get "options", to: "pages#options", as: "options"
  get "landing", to: "pages#landing"
  # get "groups/:id", to: "groups#show", as: "group"
  # get "usertasks/:id", to: "tasks#userstasks", as: "usertasks"
  # get "groups/:group_id", to: "shopping_lists#new_item", as: "newitem"
end

app/views/shared/_button_salmon.html.erb
<a class="btn btn-ghost" href="#">Write a story</a>

app/views/shared/_card_tasks_back_index.html.erb
   <div class="container row d-flex justifycontent-between">
    <% @missed_tasks.each do |task| %>
      <div class="card_tasks_up_index">
        <div class="card-a"><%= "X" %></div>
        <div class="card-b"><%= task.name %></div>
        <div class="card-c"><%= task.deadline.strftime("%d.%m.%Y") %></div>
        <div class="card-d"><%= render "shared/current_user_index_avatar" %></div>
      </div>
    <% end %>

  </div>

app/views/shared/_card_tasks_up_index.html.erb
   <div class="container row d-flex justifycontent-between">
    <% @upcoming_tasks.each do |task| %>
      <div class="card_tasks_up_index">
        <div class="card-a"><%= "X" %></div>
        <div class="card-b"><%= task.name %></div>
        <div class="card-c"><%= task.deadline.strftime("%d.%m.%Y") %></div>
        <div class="card-d"><%= render "shared/current_user_index_avatar" %></div>
      </div>
    <% end %>

  </div>

app/views/shared/_current_user_index_avatar.html.erb
<div class="current_user_index_avatar">
  <i class="fa-solid fa-dog fa-xl" style="color:#DF6C4F" class="align-center"></i>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-bottom">
  <div class="container-fluid">

    <%# <% if params[:controller] == "pages" %>
          <%# <%= active_link_to root_path, active: true, class: "navbar-brand"  do %>
          <%# <i class="fa-solid fa-house fa-xl"></i> %>
          <%# <% end %>
    <%# <% else %>
        <%# <%= active_link_to root_path, active: false, class: "navbar-brand"  do %>
          <%# <i class="fa-solid fa-house fa-xl"></i>
        <% end %>
    <%# <% end %>


    <% if params[:controller] == "groups" %>
          <%= active_link_to groups_path, active: true, class: "navbar-brand"  do %>
          <i class="fa-solid fa-people-group fa-xl"></i>
          <% end %>
    <% else %>
          <%= active_link_to groups_path, active: false, class: "navbar-brand"  do %>
          <i class="fa-solid fa-people-group fa-xl"></i>
          <% end %>
    <% end %>


    <% if MultipleGroup.find_by(user: current_user) %>
      <% group_id = MultipleGroup.find_by(user: current_user).group_id %>
        <% if params[:controller] == "pages" && params[:action] == "dashboard" %>
          <%= active_link_to dashboard_group_path(group_id), active: true, class: "navbar-brand"  do %>
          <i class="fa-solid fa-chart-pie"></i>
          <% end %>
      <% else %>
          <%= active_link_to dashboard_group_path(group_id), active: false, class: "navbar-brand"  do %>
          <i class="fa-solid fa-chart-pie"></i>
          <% end %>
      <% end %>
    <% end %>


    <% if MultipleGroup.find_by(user: current_user) %>
      <% group_id = MultipleGroup.find_by(user: current_user).group_id %>
        <% if params[:controller] == "tasks" && params[:action] == "usertasks" %>
          <%= active_link_to group_tasks_path(group_id, tasks), active: true, class: "navbar-brand"  do %>
          <i class="fa-solid fa-list-check fa-xl"></i>
          <% end %>
      <% else %>
          <%= active_link_to group_tasks_path(group_id), active: false, class: "navbar-brand"  do %>
          <i class="fa-solid fa-list-check fa-xl"></i>
          <% end %>
      <% end %>
    <% end %>

    <% if MultipleGroup.find_by(user: current_user) %>
      <% group_id = MultipleGroup.find_by(user: current_user).group_id %>
        <% if params[:controller] == "groups" && params[:action] == "show" %>
          <%= active_link_to group_path(group_id), active: true, class: "navbar-brand"  do %>
          <i class="fa-solid fa-house fa-xl"></i>
          <% end %>
      <% else %>
          <%= active_link_to group_path(group_id), active: false, class: "navbar-brand"  do %>
          <i class="fa-solid fa-house fa-xl"></i>
          <% end %>
      <% end %>
    <% end %>


    <% if user_signed_in? %>
      <%= active_link_to destroy_user_session_path,  data: {turbo_method: :delete}  do %>
      <i class="fa-solid fa-person-walking-arrow-right fa-xl"></i>
      <% end %>
    <% else %>
      <%= active_link_to new_user_session_path  do %>
      <i class="fa-solid fa-arrow-right-to-bracket fa-xl"></i>
      <% end %>
    <% end %>

    <%# <%= link_to group_fixed_costs_path, class: "navbar-brand"  do %>
      <%# <i class="fa-solid fa-euro-sign fa-xl" style=color:#23c560></i>
    <% end %>

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" ></span>
    </button> %>


  </div>
</div>

app/views/shared/_navbar_login.html.erb
          <li class="nav-item dropup">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-user fa-xl" style=color:#23c560></i>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", "#", class: "dropdown-item" %>
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>


  </div>
</div>

app/views/shared/_tasks_card.html.erb
<div class="container">
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
</div>