config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    collection do

      get :join
      post :join_group
    end

    member do
      get :dashboard
    end



     resources :shopping_lists, only: [:index, :new, :create, :show] do
        collection do
        get :new_item
        get :pre_selection
        end

        resources :bought_items, only: [:index, :new, :create, :show]

      end

    resources :tasks, only: [:index, :new, :create, :show] do
      member do
        get :usertasks
        patch :progress
        patch :finish_task

      end
    end

    resources :fixed_costs, only: [:index, :new, :create, :show]
  end
  get "options", to: "pages#options", as: "options"
  get "landing", to: "pages#landing"
  # get "groups/:id", to: "groups#show", as: "group"
  # get "usertasks/:id", to: "tasks#userstasks", as: "usertasks"
  # get "groups/:group_id", to: "shopping_lists#new_item", as: "newitem"
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :group, optional: true
  has_many :products, through: :bought_items
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController

  def index
    @group = Group.find(params[:group_id])
    @shopping_list = ShoppingList.find_by(group: @group)
    @bought_items = BoughtItem.where(shopping_list: @shopping_list)

    @total = @bought_items.map do |bought_item|
        bought_item.product.price
    end.reduce(0){|a,b| a + b }




  end

  def new
    @user = current_user
    @shopping_list = ShoppingList.new
    @selected_products = params[:category][:category].drop(1)
    @products = @selected_products.map do |id|
      Product.find(id)
    end

  end

  def new_item
    @user = current_user
    @shopping_list = ShoppingList.new
    # @add_product = params[:category][:product]
    # @add_quantity = params[:category][:quantity]
    # raise
    # raise
  end

  def create
    @shopping_list = ShoppingList(shopping_params)
    # raise
  end

  def pre_selection
    @shopping_list = ShoppingList.find_by(group_id: params[:group_id])
    @products = Product.all
    @group = Group.find(params[:group_id])

  end

  private

  def shopping_params
    params.require(:shopping_list).permit(:category)
  end

  def shopping_newitem
    params.require(:shopping_list).permit(group_id)
  end
end

app/views/shopping_lists/index.html.erb
<div class="return-arrow mt-5 mr-5">
    <%= link_to group_path(params[:group_id]) do %>
    <i class="fa-solid fa-chevron-left" style="color:#21C560; font-size: 35px; cursor: pointer;" class="align-center"></i>
    <% end %>
</div>

  <div class="animated fadeInDown">

      <div class="plus-wrapper">
        <%# <%= link_to group_bought_items_path do %>
        <%= link_to pre_selection_group_shopping_lists_path(@group, shopping_list: @shopping_list)  do %>
          <i class="fa-solid fa-square-plus fa-2xl" style="color:#23c560; text-align:center; font-size:50px"></i>
         <% end %>
      </div>




<div class="total-wrapper">
  <h1>Total</h1>
  <h1 style="color:#adadad"><%= @total.round(2) %> €</h1>
</div>
</div>

<div class="animated fadeInUp">
  <% @bought_items.each do |bought_item| %>
    <div class="bought-item-card mb-4">
      <div class="bi-padding-wrapper">
      <div class="bi-spacer-a">
        <div>

        <h3><%= bought_item.product.name %></h3>
        <span style="color:black; position: relative;top: -5px;font-weight:300;">bought by <%= bought_item.user.first_name %></span>
        </div>
       <div class="bought-item-img-bg">
          <%= image_tag "#{bought_item.product.name.downcase}.png" %>
        </div>
       </div>
        <div class="items-details-wrapper">

          <h5><%= bought_item.product.price %> €</h5>
        </div>

      </div>
    </div>
  <% end %>
</div>




<%# <%= image_tag 'icons/milk.svg', width: 25, height: 25 %>
<%# collection: @product.map {|product|
            #    [product.name,product.id,
            #    image_tag:url(#{image_path "icons/#{product.name.downcase}.svg"})"]}%>

app/views/shopping_lists/new.html.erb
<div class="wrapper-total" >
  <div class="wrapper-overview">
    <div class="new-wrapper" >
      <%# <h1>Shopping list Overview(New)</h1> %>
      <% @products.each do |product| %>
        <div class="container-banner" data-controller="quantity">
          <div class="banner-item">
            <%= product.name %>
            <span data-quantity-target="price"><%= product.price%></span>
          </div>
          <div class="icon-placeholder">
          <%= image_tag("/app/assets/images/icons/png/baguette.png", width: '40px', height: '40px') %>
            <%# <i class="fa-regular fa-face-smile"></i> %>
          </div>

          <div class="price-banner">
            <div class="total-banner">
              <span style="width: 40px" data-quantity-target="total" class="badge badge-primary badge-pill">0</span>
            </div>

            <div class="cart-totals" >
              <input type="button" value="-" id="minus-button" for="quantity" data-quantity-target="minus">
              <input class="w-50" type="number" id="quantity" value="1" min="0"  data-quantity-target="input">
              <input type="button" value="+" id="plus-button" for="quantity"  data-quantity-target="plus">
            </div>

          </div>

          </div>
      <%end%>
      <%#<h1><span data-quantity-target="superTotal" data-action="change->quantity#calculateTotal">0</span></h1>  %>
    </div>
  </div>

  <div class="wrapper-choice ">
    <%= link_to "Confirm Choice", group_bought_items_path%>
  </div>
</div>

app/views/shopping_lists/new_item.html.erb
<h1>New product</h1>
<%= simple_form_for :category, url: new_item_group_shopping_lists_path(), method: :get do |f|%>
  <%= f.input :product, label: 'Product name' %>
  <%= f.input :quantity, label: 'Quantity', collection: 1..8%>
  <%= f.button :submit, value: 'Add to cart', class:"container-basket" %>
<% end %>
<%# <% raise %>
<div class="banner-other-item">
  <h5>Add another item</h5>
</div>

app/views/shopping_lists/pre_selection.html.erb
<div class="container-init">
      <%# <div class="plus-wrapper"> %>
        <%# <%= link_to group_bought_items_path do %>
        <div class="return-arrow" style = "margin-bottom: 80px">
          <%= link_to group_shopping_lists_path do %>
          <i class="fa-solid fa-chevron-left" style="color:#21C560; font-size: 35px; cursor: pointer;" class="align-center"></i>
          <% end %>
        <%# </div> %>

      </div>
  <div class="container-form">
    <%= simple_form_for :category, url: new_group_shopping_list_bought_item_path(@group, @shopping_list), method: :get do |f| %>
      <%= f.input :category, legend_tag: false,
                as: :check_boxes,
                collection_wrapper_tag: 'div',
                collection_wrapper_class: 'category-wrapper',
                item_wrapper_class: 'category-item',
                input_html: {class: 'category-selector rounded', multiple: true },
              # collection: @product
              collection: @products.map {|product|[product.name, product.id, style:"background-image:url(#{image_path "icons/png/#{product.name.downcase}.png"})"]} %>
      <div class="container-end">
        <%= f.submit "Check Basket", class:"container-basket"%>
      </div>
    <% end %>
  </div>
</div>

app/views/shopping_lists/show.html.erb
<h1>Your products to buy🥫</h1>

app/views/shopping_lists/temp.html.erb
<h1>Shopping list Overview(New)</h1>
<%#
<%= simple_form_for :category, url: group_shopping_list_path(:group_id, :id), method: :get do |f|%>
<%= f.input :category,
            as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector', multiple: true },
            collection: @products,
            options: [[:quantity, 1..5]]
            %>

  <%= f.simple_fields_for :products do |product| %>
  <%= f.input :quantity %>
  <% end %>

<%=f.submit "Confirm selections", :class => 'btn btn-outline-dark'%>
<% end %> %>